### ISSUE TITLE
Failed to install the GitPython package in the correct Python environment

### ISSUE THREAD

**Issue by alessandroperilli** [deroberon/demofusion-comfyui#4]
Hi. Thanks for developing this new node. Very interested in trying it, but I'm receiving the following error immediately after the installation and at every restart:

> ERROR Demofusion: Attempting to reinstall dependencies using an alternative method.
> ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
> ERROR Demofusion: Failed to install the GitPython package in the correct Python environment.

I have a dozen custom nodes, but this is the first time I have a similar issue. I also tried to install GitPython manually, obviously in the ComfyUI venv, without success. 

Any guidance would be appreciated.

**Comment by deroberon** [comment]
This error happens because, even after to try pip install the dependencies, there's still an error in the initialization part of the custom node.

What I usually do for test is: 
-> Download a vanila comfyui install file, with a complete separate env from here : https://github.com/comfyanonymous/ComfyUI/releases/download/latest/ComfyUI_windows_portable_nvidia_cu121_or_cpu.7z
-> Run it a first time to see if everything is ok. (using run_nvidia_gpu.bat)
-> Git clone the repo in the ComfyUI/custom_nodes folder
-> Start it again (using run_nvidia_gpu.bat)

I just follow this steps right now, and everything seems to work in the last commited version. 

I don't know if it can be something related to your env, like torch version, OS, or even some conflicting nodes.... We have to investigate more.

Please could you try the steps above on your machine and tell me what happened? Meanwhile, if you could provide some details about your SO, Comfyui version, python version... it would be helpful (and also the complete stacktrace :)

**Comment by alessandroperilli** [comment]
I successfully installed DemoFusion in a new environment. So, there's something conflicting with this node suite in my usual working environment.

This is the full log generated in the working environment:

> ## Demofusion: installing dependencies
>  Requirement already satisfied: diffusers~=0.21.4 in ./venv/lib/python3.11/site-packages (from -r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (0.21.4)
>  Requirement already satisfied: matplotlib in ./venv/lib/python3.11/site-packages (from -r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 2)) (3.8.2)
>  Requirement already satisfied: Pillow in ./venv/lib/python3.11/site-packages (from diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (9.5.0)
>  Requirement already satisfied: filelock in ./venv/lib/python3.11/site-packages (from diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (3.13.1)
>  Requirement already satisfied: huggingface-hub>=0.13.2 in ./venv/lib/python3.11/site-packages (from diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (0.19.4)
>  Requirement already satisfied: importlib-metadata in ./venv/lib/python3.11/site-packages (from diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (6.8.0)
>  Requirement already satisfied: numpy in ./venv/lib/python3.11/site-packages (from diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (1.26.2)
>  Requirement already satisfied: regex!=2019.12.17 in ./venv/lib/python3.11/site-packages (from diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (2023.10.3)
>  Requirement already satisfied: requests in ./venv/lib/python3.11/site-packages (from diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (2.31.0)
>  Requirement already satisfied: safetensors>=0.3.1 in ./venv/lib/python3.11/site-packages (from diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (0.4.0)
>  Requirement already satisfied: contourpy>=1.0.1 in ./venv/lib/python3.11/site-packages (from matplotlib->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 2)) (1.2.0)
>  Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.11/site-packages (from matplotlib->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 2)) (0.12.1)
>  Requirement already satisfied: fonttools>=4.22.0 in ./venv/lib/python3.11/site-packages (from matplotlib->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 2)) (4.45.0)
>  Requirement already satisfied: kiwisolver>=1.3.1 in ./venv/lib/python3.11/site-packages (from matplotlib->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 2)) (1.4.5)
>  Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.11/site-packages (from matplotlib->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 2)) (23.2)
>  Requirement already satisfied: pyparsing>=2.3.1 in ./venv/lib/python3.11/site-packages (from matplotlib->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 2)) (3.1.1)
>  Requirement already satisfied: python-dateutil>=2.7 in ./venv/lib/python3.11/site-packages (from matplotlib->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 2)) (2.8.2)
>  Requirement already satisfied: fsspec>=2023.5.0 in ./venv/lib/python3.11/site-packages (from huggingface-hub>=0.13.2->diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (2023.10.0)
>  Requirement already satisfied: tqdm>=4.42.1 in ./venv/lib/python3.11/site-packages (from huggingface-hub>=0.13.2->diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (4.66.1)
>  Requirement already satisfied: pyyaml>=5.1 in ./venv/lib/python3.11/site-packages (from huggingface-hub>=0.13.2->diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (6.0.1)
>  Requirement already satisfied: typing-extensions>=3.7.4.3 in ./venv/lib/python3.11/site-packages (from huggingface-hub>=0.13.2->diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (4.8.0)
>  Requirement already satisfied: six>=1.5 in ./venv/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 2)) (1.16.0)
>  Requirement already satisfied: zipp>=0.5 in ./venv/lib/python3.11/site-packages (from importlib-metadata->diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (3.17.0)
>  Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.11/site-packages (from requests->diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (3.3.2)
>  Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.11/site-packages (from requests->diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (3.4)
>  Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.11/site-packages (from requests->diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (1.26.18)
>  Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.11/site-packages (from requests->diffusers~=0.21.4->-r xyz/ComfyUI/custom_nodes/demofusion-comfyui/requirements.txt (line 1)) (2023.11.17)
> [!]
> [!] [notice] A new release of pip is available: 23.3.1 -> 23.3.2
> [!] [notice] To update, run: pip install --upgrade pip
> ## [ERROR] Demofusion: Attempting to reinstall dependencies using an alternative method.
> [!] ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
> [!]
> [!] [notice] A new release of pip is available: 23.3.1 -> 23.3.2
> [!] [notice] To update, run: pip install --upgrade pip
> ## [ERROR] Demofusion: Failed to install the GitPython package in the correct Python environment. Please install it manually in the appropriate environment. (You can seek help at https://app.element.io/#/room/%23comfyui_space%3Amatrix.org)
> Traceback (most recent call last):
>   File "xyz/ComfyUI/custom_nodes/demofusion-comfyui/__init__.py", line 42, in <module>
>     from .demofusion import NODE_CLASS_MAPPINGS
>   File "xyz/ComfyUI/custom_nodes/demofusion-comfyui/demofusion.py", line 19, in <module>
>     from pipeline_demofusion_sdxl import DemoFusionSDXLStableDiffusionPipeline
>   File "xyz/ComfyUI/custom_nodes/demofusion-comfyui/pipeline_demofusion_sdxl.py", line 55, in <module>
>     from .watermark import StableDiffusionXLWatermarker
> ImportError: attempted relative import with no known parent package
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "xyz/ComfyUI/custom_nodes/demofusion-comfyui/__init__.py", line 52, in <module>
>     from .demofusion import NODE_CLASS_MAPPINGS
>   File "xyz/ComfyUI/custom_nodes/demofusion-comfyui/demofusion.py", line 19, in <module>
>     from pipeline_demofusion_sdxl import DemoFusionSDXLStableDiffusionPipeline
>   File "xyz/ComfyUI/custom_nodes/demofusion-comfyui/pipeline_demofusion_sdxl.py", line 55, in <module>
>     from .watermark import StableDiffusionXLWatermarker
> ImportError: attempted relative import with no known parent package
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "xyz/ComfyUI/custom_nodes/demofusion-comfyui/__init__.py", line 58, in <module>
>     from .demofusion import NODE_CLASS_MAPPINGS
>   File "xyz/ComfyUI/custom_nodes/demofusion-comfyui/demofusion.py", line 19, in <module>
>     from pipeline_demofusion_sdxl import DemoFusionSDXLStableDiffusionPipeline
>   File "xyz/ComfyUI/custom_nodes/demofusion-comfyui/pipeline_demofusion_sdxl.py", line 55, in <module>
>     from .watermark import StableDiffusionXLWatermarker
> ImportError: attempted relative import with no known parent package
> ## Demofusion: installing dependencies done.
> Skip xyz/ComfyUI/custom_nodes/demofusion-comfyui module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.

**Comment by deroberon** [comment]
Hi, 

I don't know when you did the git clone or downloaded the repo, but just yesterday I did I change that could have solved exactly this issue.

Could you try download or update the plugin and try again in your env please? I believe that now it could work. (Or at least give a different error ;-) )

**Comment by alessandroperilli** [comment]
Yep. Uninstalling/reinstalling the node suite solved the problem. No more installation errors. Thank you!

**Comment by deroberon** [comment]
Anytime :)
